pipeline {
  agent {
    dockerfile true
  }

  environment {
    frontendImage = ''
  }

  stages {
    stage('Preparando la compilación') {
      steps {
        echo 'Limpiando previo a la copilación'
        script {
          sh 'echo Bkj6dhBLfmv6yq_aM3r9 | cat | docker login registry.gitlab.com --username kerry --password-stdin'
        }
      }
    }

    
    stage('Compilando la imagen') {
      steps {
        echo 'Comenzamos la copilacion de frontend'
        script {
          frontendImage = docker.build("registry.gitlab.com/sebastianrh.sarh/solemne2_g1", "./docker -f ./.docker/Dockerfile")
        }
      }
    }
  }
}