version: '3.5'
services:
  angular:
    image: registry.gitlab.com/sebastianrh.sarh/solemne2_g1
    deploy:
      placement:
        constraints: [node.role==worker]
      labels:
        traefik.http.routers.backend.rule: Host(`angular.rockstart.cl)
        traefik.http.routers.backend.middlewares: https-redirect@file
        traefik.http.services.backend.loadbalancer.server.port: 80
        traefik.http.services.backend.priority: 1
        traefik.docker.network: traefik-net
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true
