version: '3.5'
services:
  chorizord:
    image: registry.gitlab.com/sebastianrh.sarh/solemne2_g1
    command:
      - --entrypoints.web.address=:80
      - --providers.docker.swarmMode=yes
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        traefik.http.routers.chorizord.rule: Host(`chorizord.rockstart.cl`)
        traefik.http.routers.chorizord.middlewares: https-redirect@file
        traefik.http.services.chorizord.loadbalancer.server.port: 80
        traefik.docker.network: traefik-net
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true